SELECT B.CATEGORY,
       Sum(SALES) AS TOTAL_SALES
FROM   BOOK_SALES AS BS
       JOIN BOOK AS B
         ON BS.BOOK_ID = B.BOOK_ID
WHERE  SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP  BY B.CATEGORY
ORDER  BY B.CATEGORY 