SELECT ROUTE,
       CONCAT(Round(Sum(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE,
       CONCAT(Round(Avg(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM   SUBWAY_DISTANCE
GROUP  BY ROUTE
ORDER  BY Round(Sum(D_BETWEEN_DIST), 1) DESC 