SELECT Count(*)    AS FISH_COUNT,
       Max(LENGTH) AS MAX_LENGTH,
       FISH_TYPE
FROM   (SELECT ID,
               FISH_TYPE,
               IFNULL(LENGTH, 10) AS LENGTH
        FROM   FISH_INFO) AS T
GROUP  BY FISH_TYPE
HAVING Avg(LENGTH) >= 33
ORDER  BY FISH_TYPE 