SELECT G3.ID
FROM   (SELECT *
        FROM   ECOLI_DATA AS G1
        WHERE  PARENT_ID IS NULL) AS G1
       JOIN ECOLI_DATA AS G2
         ON G2.PARENT_ID = G1.ID
       JOIN ECOLI_DATA AS G3
         ON G3.PARENT_ID = G2.ID
ORDER  BY 1 