SELECT PRODUCT_ID,
       PRODUCT_NAME,
       PRICE * Sum(AMOUNT) AS TOTAL_SALES
FROM   (SELECT O.PRODUCT_ID,
               PRODUCT_NAME,
               PRICE,
               AMOUNT
        FROM   FOOD_ORDER AS O
               JOIN FOOD_PRODUCT AS P
                 ON O.PRODUCT_ID = P.PRODUCT_ID
        WHERE  PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31') AS T
GROUP  BY PRODUCT_ID
ORDER  BY TOTAL_SALES DESC,
          PRODUCT_ID ASC 