SELECT P.PRODUCT_CODE,
       Sum(P.PRICE * OS.SALES_AMOUNT) AS SALES
FROM   OFFLINE_SALE AS OS
       JOIN PRODUCT AS P
         ON OS.PRODUCT_ID = P.PRODUCT_ID
GROUP  BY P.PRODUCT_ID
ORDER  BY SALES DESC,
          P.PRODUCT_CODE 