SELECT J.FLAVOR
FROM   (SELECT FLAVOR,
               SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM   JULY
        GROUP  BY FLAVOR) AS J
       JOIN FIRST_HALF AS F
         ON J.FLAVOR = F.FLAVOR
ORDER  BY ( J.TOTAL_ORDER + F.TOTAL_ORDER ) DESC
LIMIT  3 