SELECT FI.ID,
       FNI.FISH_NAME,
       FI.LENGTH
FROM   FISH_INFO AS FI
       JOIN (SELECT FISH_TYPE,
                    Max(LENGTH) AS MAX_LENGTH
             FROM   FISH_INFO
             GROUP  BY FISH_TYPE) AS MAX_LEN
         ON FI.FISH_TYPE = MAX_LEN.FISH_TYPE
            AND FI.LENGTH = MAX_LEN.MAX_LENGTH
       JOIN FISH_NAME_INFO AS FNI
         ON FI.FISH_TYPE = FNI.FISH_TYPE
ORDER  BY FI.ID 