SELECT B.YEAR,
       MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
       ID
FROM   ECOLI_DATA A
       JOIN (SELECT Year(DIFFERENTIATION_DATE) YEAR,
                    Max(SIZE_OF_COLONY)        MAX_SIZE
             FROM   ECOLI_DATA
             GROUP  BY Year(DIFFERENTIATION_DATE)) B
         ON Year(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER  BY YEAR ASC,
          YEAR_DEV ASC 