# 첫번째 풀이
-- SELECT DISTINCT CAR_ID
-- FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE  CAR_ID IN (SELECT CAR_ID
--                   FROM   CAR_RENTAL_COMPANY_CAR
--                   WHERE  CAR_TYPE = '세단')
--        AND Month(START_DATE) = 10
-- ORDER  BY CAR_ID DESC 

SELECT DISTINCT H.CAR_ID
FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
       JOIN CAR_RENTAL_COMPANY_CAR AS C
         ON H.CAR_ID = C.CAR_ID
WHERE  C.CAR_TYPE = '세단'
       AND Month(H.START_DATE) = 10
ORDER  BY H.CAR_ID DESC 